// grid_feeder.js
// -----------------------------------------------------------------------------
// Pushes a synthetic, seeded 24-hour frequency/voltage trace to the deployed
// GridStabilityOracle -- one real updateCondition() transaction per simulated
// hour (24 total). This is stronger evidence than the earlier two-point test
// because the intermediate hours are NOT hand-picked to land on either side
// of G_THRESHOLD -- only two of the 24 points are deliberately engineered
// stress events (one frequency-driven, one voltage-driven); the rest are
// small, realistic normal-operation noise around 60Hz/120V.
//
// IMPORTANT SCOPE NOTE (for the manuscript): this is still a SYNTHETIC trace
// generated by this script, not telemetry from a real PMU or utility feed.
// What it demonstrates is that the on-chain mechanism responds correctly to
// a time-varying signal it wasn't tuned point-by-point to react to -- not
// that a live grid-data integration exists. See the dev conversation / the
// manuscript's Limitations section.
//
// Usage:
//   1. npm install web3 dotenv   (if not already installed)
//   2. .env needs INFURA_PROJECT_ID and PRIVATE_KEY (must hold ORACLE_ROLE --
//      i.e. must be the account that deployed GridStabilityOracle)
//   3. node grid_feeder.js
//
// Output: grid_feeder_results.json, written incrementally (one hour at a
// time), so a crash partway through still leaves everything completed so
// far on disk.
//
// Cost/time heads-up: 24 sequential transactions at ~12s Sepolia confirmation
// each -- roughly 5 minutes real time, 24x the gas of a single call. Trivial
// on testnet ETH, just not instantaneous.
// -----------------------------------------------------------------------------

require('dotenv').config();
const { Web3 } = require('web3');
const fs = require('fs');

const ORACLE_ADDRESS = "0x9580429807f611a286255ff325e7c6812343d340"; // GridStabilityOracle
const OUTPUT_FILE = "grid_feeder_results.json";
const ETH_USD_PRICE = 3200; // static approximation, update as needed

const ORACLE_ABI = [
    { "inputs": [{ "internalType": "uint256", "name": "frequency", "type": "uint256" }, { "internalType": "uint256", "name": "voltage", "type": "uint256" }], "name": "updateCondition", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [], "name": "getStabilityScore", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
    { "inputs": [], "name": "isGridStressed", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
];

// ============================================================================
// Seeded PRNG (mulberry32) so the "random" noise is exactly reproducible --
// anyone re-running this with the same SEED gets the identical 24 readings.
// ============================================================================
const SEED = 20260913;
function mulberry32(seed) {
    return function () {
        seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
        let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}
const rng = mulberry32(SEED);
function gaussian() {
    // Box-Muller, using the seeded uniform RNG above
    const u1 = Math.max(rng(), 1e-9), u2 = rng();
    return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
}

// ============================================================================
// Build the 24-hour synthetic trace
// ============================================================================
const NOMINAL_FREQ = 60000;   // 60.000 Hz, millihertz-scaled
const NOMINAL_VOLT = 120000;  // 120.000 V, millivolt-scaled

// Deliberately engineered stress events -- one per trigger path, so both are
// independently exercised. All other hours are just noise.
const STRESS_EVENTS = {
    14: { frequency: 59000, voltage: NOMINAL_VOLT, label: "frequency-driven dip (generation loss)" },
    20: { frequency: NOMINAL_FREQ, voltage: 108000, label: "voltage-driven sag (evening peak brownout)" },
};

function buildTrace() {
    const trace = [];
    for (let hour = 0; hour < 24; hour++) {
        if (STRESS_EVENTS[hour]) {
            trace.push({ hour, ...STRESS_EVENTS[hour], engineered: true });
        } else {
            // Normal operation noise: ~0.03 Hz std dev (clipped to +-0.08 Hz),
            // ~0.3 V std dev (clipped to +-1.0 V) -- small, realistic jitter.
            const freqDev = Math.max(-80, Math.min(80, Math.round(gaussian() * 30)));
            const voltDev = Math.max(-1000, Math.min(1000, Math.round(gaussian() * 300)));
            trace.push({
                hour,
                frequency: NOMINAL_FREQ + freqDev,
                voltage: NOMINAL_VOLT + voltDev,
                label: "normal operation",
                engineered: false,
            });
        }
    }
    return trace;
}

// ============================================================================
// Main
// ============================================================================
async function main() {
    console.log("=".repeat(78));
    console.log("SYNTHETIC 24-HOUR GRID FEEDER -- GridStabilityOracle");
    console.log(`Seed: ${SEED} (reproducible)`);
    console.log("=".repeat(78));

    const web3 = new Web3(`https://sepolia.infura.io/v3/${process.env.INFURA_PROJECT_ID}`);
    web3.defaultReturnFormat = { number: 'str', bytes: 'HEX' };

    let privateKey = (process.env.PRIVATE_KEY || "").trim();
    if (!privateKey) { console.error("Set PRIVATE_KEY in .env"); process.exit(1); }
    if (privateKey.length === 64) privateKey = '0x' + privateKey;
    const account = web3.eth.accounts.privateKeyToAccount(privateKey);
    web3.eth.accounts.wallet.add(account);
    const from = account.address;

    console.log(`Account: ${from}\n`);

    const oracle = new web3.eth.Contract(ORACLE_ABI, ORACLE_ADDRESS);
    const trace = buildTrace();

    const results = {
        metadata: {
            startedAt: new Date().toISOString(),
            network: "Sepolia",
            oracleAddress: ORACLE_ADDRESS,
            account: from,
            seed: SEED,
            note: "SYNTHETIC trace, not real telemetry. 22/24 points are unengineered noise around nominal; hours 14 and 20 are deliberate stress events (frequency- and voltage-driven respectively). Every entry is a real on-chain transaction.",
        },
        readings: [],
    };

    function save() {
        fs.writeFileSync(OUTPUT_FILE, JSON.stringify(results, null, 2));
    }

    for (const point of trace) {
        process.stdout.write(`Hour ${String(point.hour).padStart(2, '0')}: freq=${point.frequency / 1000}Hz, volt=${point.voltage / 1000}V (${point.label}) ... `);
        const reading = { ...point };
        try {
            const gasPriceBefore = await web3.eth.getGasPrice();
            const m = oracle.methods.updateCondition(point.frequency, point.voltage);
            const gas = await m.estimateGas({ from }).catch(() => 200000n);
            const receipt = await m.send({ from, gas });

            reading.success = true;
            reading.txHash = receipt.transactionHash;
            reading.blockNumber = Number(receipt.blockNumber);
            reading.gasUsed = Number(receipt.gasUsed);
            reading.gasPriceGwei = Number(web3.utils.fromWei(gasPriceBefore, "gwei"));
            reading.txCostETH = (reading.gasUsed * Number(gasPriceBefore)) / 1e18;
            reading.txCostUSD = reading.txCostETH * ETH_USD_PRICE;

            // Pinned to the exact block just confirmed -- avoids the RPC
            // read-after-write lag seen in the earlier validation run.
            const score = await oracle.methods.getStabilityScore().call({}, reading.blockNumber);
            const isStressed = await oracle.methods.isGridStressed().call({}, reading.blockNumber);
            reading.score = Number(score) / 1e18;
            reading.isStressed = isStressed;

            console.log(`G=${reading.score.toFixed(3)} ${isStressed ? '[STRESSED]' : ''}`);
        } catch (err) {
            reading.success = false;
            reading.error = err.message;
            console.log(`FAILED: ${err.message}`);
        }
        results.readings.push(reading);
        save();
    }

    results.metadata.finishedAt = new Date().toISOString();
    results.summary = {
        totalHours: trace.length,
        successCount: results.readings.filter(r => r.success).length,
        failureCount: results.readings.filter(r => !r.success).length,
        stressedHoursDetected: results.readings.filter(r => r.success && r.isStressed).map(r => r.hour),
        totalGasUsed: results.readings.reduce((s, r) => s + (r.gasUsed || 0), 0),
    };
    save();

    console.log("\n" + "=".repeat(78));
    console.log(`Done. ${results.summary.successCount}/${trace.length} hourly readings succeeded.`);
    console.log(`Stressed hours detected on-chain: [${results.summary.stressedHoursDetected.join(", ")}]`);
    console.log(`(Engineered stress hours were: [${Object.keys(STRESS_EVENTS).join(", ")}])`);
    console.log(`Results written to ${OUTPUT_FILE}`);
    console.log("=".repeat(78));
}

main().catch(console.error);
